name: Auto Publish Bible Video

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq git python3-pip
          pip3 install gtts

      - name: Generate narration (gTTS)
        run: |
          echo "from gtts import gTTS" > narrate.py
          echo "text = open('script.txt', 'r', encoding='utf-8').read()" >> narrate.py
          echo "tts = gTTS(text, lang='en')" >> narrate.py
          echo "tts.save('narration.mp3')" >> narrate.py
          python3 narrate.py
          ffmpeg -y -i narration.mp3 narration.wav

      - name: Download 3D-styled image from Unsplash
        run: |
          URL=$(curl -sI "https://source.unsplash.com/featured/1280x720/?bible,Jesus,3d,render,scripture,cross,heaven" | awk '/^location:/ {print $2}' | tr -d '\r')
          if [ -z "$URL" ]; then
            echo "Failed to fetch redirect URL from Unsplash"
            exit 1
          fi
          curl -sL "$URL" --output image.jpg || { echo "Download failed"; exit 1; }

      - name: Assemble video
        run: |
          ffmpeg -y -loop 1 -t 30 -i image.jpg -i narration.wav \
            -c:v libx264 -c:a aac -shortest video.mp4

      - name: Commit and push video.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add video.mp4
          git commit -m "downloads the actual image file directly"
          git push origin main
