name: Auto Publish Bible Video

on:
  schedule:
    - cron: '0 9 * * *'    # daily at 09:00 UTC
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate narration (TTS)
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        curl -s -X POST "https://api-inference.huggingface.co/models/tts_models/en/ljspeech/tacotron2-DDC" \
          -H "Authorization: Bearer $HF_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"inputs\": \"$(sed ':a;N;$!ba;s/\"/\\\"/g;s/\n/\\n/g' script.txt)\"}" \
          --output narration.wav

    - name: Generate image (Stable Diffusion)
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        curl -s -X POST "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5" \
          -H "Authorization: Bearer $HF_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"inputs\": \"$(head -n1 script.txt)\"}" \
          --output image.png

    - name: Assemble video
      run: |
        ffmpeg -y -loop 1 -t 30 -i image.png -i narration.wav \
          -c:v libx264 -c:a aac video.mp4

    - name: Upload to YouTube
      uses: google-github-actions/upload-video@v1
      with:
        api_key: ${{ secrets.YT_API_KEY }}
        video_file: video.mp4
        title: "Daily Bible Reading"
        description: "Automated upload of today's Bible passage."
