name: Auto Publish Bible Video

on:
  schedule:
    - cron: '0 9 * * *'      # daily at 09:00 UTC
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Debug installed tools
      run: |
        echo "=== ffmpeg version ==="
        ffmpeg -version
        echo "=== jq version ==="
        jq --version
        echo "=== Python version ==="
        python3 --version
        echo "=== pip version ==="
        pip3 --version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg jq git python3-pip
        pip3 install gtts

    - name: Generate narration (gTTS)
      run: |
        python3 - << 'PYCODE'
from gtts import gTTS
text = open('script.txt', 'r', encoding='utf-8').read()
tts = gTTS(text, lang='en')
tts.save('narration.mp3')
PYCODE
        ffmpeg -y -i narration.mp3 narration.wav

    - name: Generate image
      run: |
        curl -s "https://source.unsplash.com/1280x720/?bible" -o image.png

    - name: Assemble video
      run: |
        ffmpeg -y -loop 1 -t 30 -i image.png -i narration.wav \
          -c:v libx264 -c:a aac video.mp4

    - name: Commit and push video.mp4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add video.mp4
        git commit -m "Add daily Bible video (gTTS + debug)"
        git push origin main
