name: Auto Publish Bible Video

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq git python3-pip
          pip3 install gtts

      - name: Generate narration (gTTS)
        run: |
          echo "from gtts import gTTS" > narrate.py
          echo "text = open('script.txt', 'r', encoding='utf-8').read()" >> narrate.py
          echo "tts = gTTS(text, lang='en')" >> narrate.py
          echo "tts.save('narration.mp3')" >> narrate.py
          python3 narrate.py
          ffmpeg -y -i narration.mp3 narration.wav

      - name: Generate image (Hugging Face)
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          curl -s -X POST "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5" \
            -H "Authorization: Bearer $HF_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"inputs":"realistic image of Jesus walking through a golden field, bright sunlight, biblical mood"}' \
            --output image.jpg

      - name: Backup image if generation failed (fallback to Unsplash)
        run: |
          if [ ! -s image.jpg ]; then
            curl -sL -o image.jpg "https://source.unsplash.com/featured/1280x720/?bible,Jesus,scripture,cross,heaven,prayer,grace,disciples,resurrection,God,hope,faith,salvation,worship,holy,church,peace,miracle,light,redemption,Messiah,love,praise,Christ,blessing,Christianity,harmony,comfort,devotion,truth,eternity"
          fi

      - name: Assemble video
        run: |
          ffmpeg -y -loop 1 -t 30 -i image.jpg -i narration.wav \
            -c:v libx264 -c:a aac -shortest video.mp4

      - name: Commit and push video.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add video.mp4
          git commit -m "Add daily Bible video"
          git push origin main
